version: "3.3"
services:
  flight_review_app:
    # image: px4flightreview
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - flight_review_data:/opt/data
      - ${PWD}/app/config_default_homelab.ini:/opt/service/config_default.ini:ro # Absolute for volume a file.
    restart: always

volumes:
  flight_review_data:
